# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_isim', models.CharField(max_length=100)),
                ('pozisyon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('yonetim', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numara', models.CharField(max_length=100)),
                ('saticiAdi', models.CharField(max_length=100)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bolum')),
                ('pazar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Pazar')),
            ],
        ),
        migrations.CreateModel(
            name='UrunAdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_isim', models.CharField(max_length=30)),
                ('pazar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Pazar')),
            ],
        ),
        migrations.CreateModel(
            name='UrunOzellikleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozellikAdi', models.CharField(max_length=10)),
                ('urunFiyati', models.CharField(max_length=10)),
                ('stok', models.PositiveIntegerField()),
                ('pazar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Pazar')),
                ('urunadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UrunAdi')),
            ],
        ),
        migrations.CreateModel(
            name='UrunTipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_ismi', models.CharField(max_length=30)),
                ('pazar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Pazar')),
                ('reyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reyon')),
            ],
        ),
        migrations.AddField(
            model_name='urunadi',
            name='urunTipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UrunTipi'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='pazar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pazar'),
        ),
    ]
